{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "twizz-service.fullname" . }}
  labels:
    {{- include "twizz-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "twizz-service.fullname" . }}-secrets
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.remoteRef }}
{{- end }}
