{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "twizz-service.fullname" . }}
  labels:
    {{- include "twizz-service.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
  {{- end }}
{{- end }}
